#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TEMPLATE_DIR="$DIR/currency_templates"

mkdir -p "$TEMPLATE_DIR"

echo "=================================================="
echo "       MANUAL IMAGE SETUP WIZARD"
echo "=================================================="
echo "Since downloading failed and the camera is weak,"
echo "you need to provide one good image for each banknote."
echo "I have created the folder for you: $TEMPLATE_DIR"
echo ""
echo "Please find images on Google Images (search '200 TL banknote front'),"
echo "and save them into this folder with these EXACT names:"
echo ""
echo "  $TEMPLATE_DIR/200.jpg"
echo "  $TEMPLATE_DIR/100.jpg"
echo "  $TEMPLATE_DIR/50.jpg"
echo "  $TEMPLATE_DIR/20.jpg"
echo "  $TEMPLATE_DIR/10.jpg"
echo "  $TEMPLATE_DIR/5.jpg"
echo ""
echo "=================================================="
echo "Opening folder now..."
xdg-open "$TEMPLATE_DIR" 2>/dev/null || echo "Opened $TEMPLATE_DIR"
echo "Once you paste the images, run './run_generate_and_train.sh'"
